# Generated by Django 3.1.1 on 2020-09-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customer_frofile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='frofile_pic',
            new_name='profile_pic',
        ),
    ]
